// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmjvqQy_z7nBGwkbVduyClx9gD3vWpwQw',
    appId: '1:577286217128:web:35f3c6af39f40072bc919d',
    messagingSenderId: '577286217128',
    projectId: 'finance-2edd4',
    authDomain: 'finance-2edd4.firebaseapp.com',
    storageBucket: 'finance-2edd4.firebasestorage.app',
    measurementId: 'G-45CM1K9HCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6CJ3x1hZ-u4cu6O04BsUb5i_ZUigouag',
    appId: '1:577286217128:android:f28cf45de46cd5fabc919d',
    messagingSenderId: '577286217128',
    projectId: 'finance-2edd4',
    storageBucket: 'finance-2edd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1MXS_ZnoI2jhfBsKR8YY4YTycSuFIdqE',
    appId: '1:577286217128:ios:0d4c8f246683b033bc919d',
    messagingSenderId: '577286217128',
    projectId: 'finance-2edd4',
    storageBucket: 'finance-2edd4.firebasestorage.app',
    iosBundleId: 'com.example.financeUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmjvqQy_z7nBGwkbVduyClx9gD3vWpwQw',
    appId: '1:577286217128:web:980eb1b6837711dcbc919d',
    messagingSenderId: '577286217128',
    projectId: 'finance-2edd4',
    authDomain: 'finance-2edd4.firebaseapp.com',
    storageBucket: 'finance-2edd4.firebasestorage.app',
    measurementId: 'G-XW6D4708D2',
  );
}
